<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="victorReddy" failures="0" tests="6" name="com.tutorialsninja.Login" time="24.150" errors="1" timestamp="2024-04-17T21:05:13 IST" skipped="1">
  <testcase classname="com.tutorialsninja.Login" name="verifyLoginWithVaildCredentails" time="5.747"/>
  <testcase classname="com.tutorialsninja.Login" name="verifyLoginWithVaildCredentails" time="4.921"/>
  <testcase classname="com.tutorialsninja.Login" name="verifyLoginwithInvalidCredentails" time="4.686"/>
  <testcase classname="com.tutorialsninja.Login" name="verifyLoginwithInvalidEmailAndValidPassword" time="5.128"/>
  <testcase classname="com.tutorialsninja.Login" name="verifyLoginwithvalidEmailAndInValidPassword" time="3.668">
    <error message="/ by zero" type="java.lang.ArithmeticException">
      <![CDATA[java.lang.ArithmeticException: / by zero
at com.tutorialsninja.Login.verifyLoginwithvalidEmailAndInValidPassword(Login.java:87)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
    </error>
  </testcase> <!-- verifyLoginwithvalidEmailAndInValidPassword -->
  <testcase classname="com.tutorialsninja.Login" name="verifyLoginwithoutProvindingCretials" time="0.000">
    <skipped/>
  </testcase> <!-- verifyLoginwithoutProvindingCretials -->
</testsuite> <!-- com.tutorialsninja.Login -->
